
# Deployment.yaml file

apiVersion: apps/v1
kind: Deployment
metadata :
  name: plasmadonor
spec:
  replicas: 3
  selector:
    matchLabels :
      app: plasmadonor
  template:
    metadata:
      labels:
        app: plasmadonor
    spec:
      containers:
      - name: plasmadonor
        image : au.icr.io/value/pda
        imagePullPolicy: Always
        ports:
        - containerPort: 5000